### ISSUE TITLE
Indents on <br /> and doesn't unindent

### ISSUE THREAD

**Issue by NickBolles** [krtnio/angular-pretty-xml#1]
Looks like a pretty simple fix, just need to add another elseIf to check for <br

**Comment by v12** [comment]
Do you mind to provide me with an example which fails to work as expected? 😉

**Comment by NickBolles** [comment]
This plunker is what I am working on and what I noticed it in
http://plnkr.co/edit/iVSFMlhuD3nYryRWuiu7?p=preview

![pretty xml bug](https://cloud.githubusercontent.com/assets/7891759/14837970/8adadd1e-0be2-11e6-9cb3-edfa89f12256.PNG)

```
function getHtml(){
  return document.querySelector('#mainuiview').outerHTML;
}
```

**Comment by v12** [comment]
@NickBolles what I can see from the plunker you posted is that you're applying _pretty-xml_ plugin to HTML (not XHTML), so such behaviour is expected because this plugin is designed to be used with XML compliant syntax whereas HTML is not as strict. And in your example `<br>` tag isn't closed, so it's recognised as an opening tag rather than empty tag, and in XHTML any empty tag should always be closed.

You can read more about differences between HTML and XHTML [here](http://www.w3schools.com/html/html_xhtml.asp).

Unfortunately, there are two ways of making it work in your case I can think about:
- use of XHTML code (not really good choice, but still an option)
- try another library to prettify your HTML (however, I can't think about any of the top of my head)

Hope it helps! If you require any further assistance, feel free to contact me 👌

**Comment by NickBolles** [comment]
Ahh. I thought it would work the same. Or with a `<br></br>` but this behaves differently. Thank you very much! Not that big of a deal in my case anyways.

**Comment by v12** [comment]
Just in case, `<br />` should also work fine :)
